Feature/dark theme
HealthPlay-EPFL/Health-Play pull request #100
Opened 2022-03-31 15:57 UTC by emonnin-epfl

2022-03-31 21:01 UTC, ozan-guven requested changes
In general, good code ! But try those changes.

2022-03-31 21:09 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/SignedInActivity.java
> +    public void onClickNight(View view) {
fixed!

2022-03-31 21:22 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +                        if (selected_Date != null && selected_Date.equals(date)) {
did it!

2022-03-31 21:23 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileActivity.java
> +                    String[] parts = birthday.split("-");
good observation, fixed it !

2022-03-31 21:25 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +                        if (selected_Date != null && selected_Date.equals(date)) {
Perfect !

2022-03-31 21:30 UTC, ozan-guven approved these changes
Perfect ! Your code is much better and I cannot find any other things to say. Good job!

2022-04-01 08:39 UTC, Antonio06188 requested changes
In many activity, in onCreate method you write the same code, you can maybe make a static method

2022-04-01 08:49 UTC, emonnin-epfl commented
did it!

2022-04-01 08:54 UTC, Antonio06188 approved these changes

2022-04-01 09:06 UTC, merged