Feature/calendar
HealthPlay-EPFL/Health-Play pull request #104
Opened 2022-04-01 09:17 UTC by Tetardfurieux

2022-04-01 09:28 UTC, Zephyr75 requested changes

2022-04-01 09:28 UTC, Zephyr75 commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +    private void constructUserStats(FirebaseUser user){
Some missing comments in this method but everything else looks more optimized and is well documented.

2022-04-01 10:05 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +    private void constructUserStats(FirebaseUser user){
Done !

2022-04-01 12:10 UTC, Zephyr75 approved these changes

2022-04-06 15:25 UTC, emonnin-epfl approved these changes

2022-04-06 15:35 UTC, merged