Create camera usage in barcode scanning using CameraX
HealthPlay-EPFL/Health-Play pull request #130
Opened 2022-04-07 15:36 UTC by ozan-guven

2022-04-07 19:52 UTC, Zephyr75 requested changes
Good code overall, good gestion of exceptions and clear explanation when catch is unneccessary! Just a couple of missing comments to fix.

2022-04-07 19:52 UTC, Zephyr75 commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +    private void bindPreview(ProcessCameraProvider cameraProvider) {
Some missing comments in the bindPreview method

2022-04-07 19:52 UTC, Zephyr75 commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +                System.out.println("YASSSSSSSSSSSSSSSS");
Please get rid of the funny prints :)

2022-04-07 19:52 UTC, Zephyr75 commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +                System.out.println("NOOOOOOOOOOOOOOOOOOOOOOOOOOOOO");
Please get rid of the funny prints :)

2022-04-08 06:54 UTC, emonnin-epfl requested changes

2022-04-08 06:54 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +                boolean ignored = file.delete();
Maybe there is no need to use a variable for the return value

2022-04-08 06:54 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +                boolean ignored = file.delete();
Maybe there is no need to use a variable for the return value

2022-04-08 06:54 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +    private ListenableFuture<ProcessCameraProvider> cameraProviderFuture;
Making it static would be a good idea

2022-04-08 06:54 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +    private PreviewView previewView;
Making it static would be a good idea

2022-04-08 08:11 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +                boolean ignored = file.delete();
I disagree with you because the IDE otherwise gives an annoying warning that the return value of the delete function is not used, but we do not need the return value of this function.

2022-04-08 08:11 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +                boolean ignored = file.delete();
I disagree with you because the IDE otherwise gives an annoying warning that the return value of the delete function is not used, but we do not need the return value of this function.

2022-04-08 08:12 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +    private PreviewView previewView;
I disagree with you because those are instance dependent and not class dependent and should hence not be static.

2022-04-08 08:22 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +                boolean ignored = file.delete();
I can see that.

2022-04-08 08:22 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +                boolean ignored = file.delete();
I can see that.

2022-04-08 08:22 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanActivity.java
> +    private PreviewView previewView;
I can see that.

2022-04-08 08:22 UTC, emonnin-epfl approved these changes

2022-04-08 08:23 UTC, Zephyr75 approved these changes

2022-04-08 09:04 UTC, merged