Feature/profile picture
HealthPlay-EPFL/Health-Play pull request #131
Opened 2022-04-07 20:15 UTC by emonnin-epfl

2022-04-07 22:30 UTC, ozan-guven requested changes
Good code in general, but look for the changes I asked. Furthermore, you should add some comments thoughout your code because it is sometimes difficult to understand what you are trying to do.

2022-04-07 22:30 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/EditProfilePictureActivity.java
> +    private DatabaseReference mDatabase = FirebaseDatabase.getInstance(Database.DATABASE_URL).getReference();
You should probably make some of those field as final static fields.

2022-04-07 22:30 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/EditProfilePictureActivity.java
> +                        Toast.makeText(this, "try again!", Toast.LENGTH_SHORT).show();
You should make the toast String into a variable.

2022-04-07 22:30 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/EditProfilePictureActivity.java
> +                StorageTask mtask = mStorage.child("profilePicture").child(user.getUid() + "jpg").putFile(uri);
Shouldn't there be a point before the "jpg", like rather ".jpg" ?

2022-04-07 22:30 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/EditProfilePictureActivity.java
> +                           return  mStorage.child("profilePicture").child(user.getUid() + "jpg").getDownloadUrl();
Same as above ? (Shouldn't there be a point before the "jpg", like rather ".jpg" ?)

2022-04-07 22:30 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/EditProfilePictureActivity.java
> +            Toast.makeText(this, "Image not selected", Toast.LENGTH_SHORT).show();
You should make this string into a variable.

2022-04-08 07:36 UTC, Antonio06188 submitted a review, later dismissed

2022-04-08 07:42 UTC, Antonio06188 requested changes

2022-04-08 07:42 UTC, Antonio06188 commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileActivity.java
> +    private DatabaseReference mDatabase = FirebaseDatabase.getInstance(Database.DATABASE_URL).getReference();
There is an object Database which have mDatabase defines like this, and later in the program you create an Object Database for use the attribute mDatabase

2022-04-08 07:42 UTC, Antonio06188 commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileActivity.java
>          FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
use mAuth

2022-04-08 08:01 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/EditProfilePictureActivity.java
> +    private DatabaseReference mDatabase = FirebaseDatabase.getInstance(Database.DATABASE_URL).getReference();
done!

2022-04-08 08:01 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/EditProfilePictureActivity.java
> +                        Toast.makeText(this, "try again!", Toast.LENGTH_SHORT).show();
Did it!

2022-04-08 08:02 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/EditProfilePictureActivity.java
> +                StorageTask mtask = mStorage.child("profilePicture").child(user.getUid() + "jpg").putFile(uri);
Yep you are right, thanks you.

2022-04-08 08:03 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/EditProfilePictureActivity.java
> +                        Toast.makeText(this, "try again!", Toast.LENGTH_SHORT).show();
Probably not necessary, i use it only once.

2022-04-08 08:03 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/EditProfilePictureActivity.java
> +            Toast.makeText(this, "Image not selected", Toast.LENGTH_SHORT).show();
Did it!

2022-04-08 08:04 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileActivity.java
> +    private DatabaseReference mDatabase = FirebaseDatabase.getInstance(Database.DATABASE_URL).getReference();
Yup i fixed it, thank you

2022-04-08 08:04 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileActivity.java
>          FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
done!

2022-04-08 08:16 UTC, ozan-guven approved these changes
Thank you ! Keep up with work !

2022-04-08 08:31 UTC, Antonio06188 approved these changes

2022-04-08 08:31 UTC, merged