Save before redesign activity
HealthPlay-EPFL/Health-Play pull request #148
Opened 2022-04-16 09:28 UTC by Zephyr75

2022-04-16 14:34 UTC, ozan-guven requested changes
Nice implementation. You can look for my comments.

2022-04-16 14:34 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/PlanthuntCameraActivity.java
> +    private static Button createLobbyButton;
As the codeclimate warning says, you should not make those variables as static (all the static fields in this class). Maybe you meant them to be final I assume ?

2022-04-16 14:34 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/PlanthuntJoinLobbyActivity.java
> +    private static Button lobbyButton;
Same as the other comment, you should not make this field a static field as this is an Android context class and does a memory leak as the codeclimat warning says.

2022-04-16 14:34 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/database/Database.java
> +                        .child("playerUid" + (nbrPlayers))
You could make a constant for this string in here.

2022-04-16 14:34 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/database/Database.java
> +                .child("password")
You could make a constant for this string.

2022-04-17 10:25 UTC, ozan-guven approved these changes
Nice job ! You didn't need to completely remove the static field variables, you could have just removed the `static` keyword but this also works !

2022-04-17 10:52 UTC, Tetardfurieux requested changes
Good code, good feature and good use of Objects.requireNonNull on DataSnapshot.
Also good documentation of the code.
However, please cleanup your code when creating a PR, + update the description of the function getLobbyId

2022-04-17 10:52 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/PlanthuntCreateLobbyActivity.java
>              }
Try to remove comments when creating a PR

2022-04-17 10:52 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/PlanthuntJoinLobbyActivity.java
> +
Remove comment

2022-04-17 10:52 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/PlanthuntJoinLobbyActivity.java
> +
You could create a function with an EditText in parameter, in order not to duplicate code

2022-04-17 10:52 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/PlanthuntJoinLobbyActivity.java
> +            }
Commented line need to be removed

2022-04-17 10:52 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/Database.java
> +    public Task checkLobbyId (String name, String password){
Wrong description of the function, please fix

2022-04-17 20:47 UTC, Tetardfurieux approved these changes
That's perfect now !

2022-04-18 12:03 UTC, merged