Transform Activity into Fragments
HealthPlay-EPFL/Health-Play pull request #151
Opened 2022-04-17 11:09 UTC by Antonio06188

2022-04-17 12:56 UTC, Tetardfurieux requested changes
Nothing to say overall, you did a great job.
However, clean all the dead code (i.e comments of past code)

2022-04-17 12:56 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileFragment.java
> +
Maybe put this function in Database Class

2022-04-17 12:56 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/GameMenuFragment.java
> +                        FragmentTransaction fragmentTransaction = getFragmentManager().beginTransaction();
Please clean the code (remove comments)

2022-04-17 12:56 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/GameMenuFragment.java
> +                        startActivity(intent, options.toBundle());*/
Remove comments

2022-04-17 12:56 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/KneetagDescriptionFragment.java
> +                        startActivity(intent, options.toBundle());*/
Remove comments

2022-04-17 12:56 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/PlanthuntDescriptionFragment.java
> +                        startActivity(intent, options.toBundle());*/
Comment

2022-04-17 12:56 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/ProfileSettingsFragment.java
> +                //startActivity(new Intent(this, HomeScreenActivity.class));
Remove

2022-04-17 12:56 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/ProfileSettingsFragment.java
> +        }
remove

2022-04-17 12:56 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/ProfileSettingsFragment.java
> +                //startActivity(new Intent(this, ProfileActivity.class));
remove

2022-04-17 12:56 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileFragment.java
> +                        startActivity(intent, options.toBundle());*/
remove

2022-04-17 14:48 UTC, Zephyr75 requested changes
Good code overall and nice fragment integration! Good understanding of layouts. Please clean up the code a bit even if it isn't necessarily your code originally.

2022-04-17 14:48 UTC, Zephyr75 commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/GameMenuFragmentTest.java
> +    public void init() throws InterruptedException {
Good decision to update test, please delete commented out old version

2022-04-17 14:48 UTC, Zephyr75 commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/ProfileSettingsFragmentTest.java
> +        text.perform(ViewActions.typeText("test"));
Please use string constants even in test methods

2022-04-17 14:48 UTC, Zephyr75 commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanFragment.java
> +                                .setTitle("Error")
Create constants for error strings

2022-04-17 14:48 UTC, Zephyr75 commented on app/src/main/java/ch/epfl/sdp/healthplay/EditProfilePictureFragment.java
> +public class EditProfilePictureFragment extends Fragment {
Please add a comment to explain what the class if used for

2022-04-18 08:43 UTC, Antonio06188 commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileFragment.java
> +
No, because functions initBirthday, initStats, initName, init the field of the text view of ProfileFragment and no the field of database, and so I think that they are in the right place

2022-04-18 09:34 UTC, Zephyr75 approved these changes

2022-04-18 11:31 UTC, Tetardfurieux approved these changes
Nice !

2022-04-18 11:32 UTC, merged