Designed planhunt layout
HealthPlay-EPFL/Health-Play pull request #170
Opened 2022-04-28 19:25 UTC by Zephyr75

2022-04-28 23:07 UTC, Tetardfurieux approved these changes
Not much to say since it's a lot of xml.
Anyway good code contribution and features !

2022-04-28 23:07 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/planthunt/PlanthuntCreateLobbyActivity.java
Good choice of explicit name

2022-04-29 06:31 UTC, ozan-guven requested changes
I don't have much to say either but you can look for my one single comment. Otherwise good job!

2022-04-29 07:52 UTC, ozan-guven approved these changes
Good job !

2022-04-29 08:18 UTC, merged