It is now possible to play kneetag
HealthPlay-EPFL/Health-Play pull request #202
Opened 2022-05-05 13:21 UTC by Aco-Hub

2022-05-05 14:55 UTC, Tetardfurieux requested changes
Good code overall, well documented.
Please remove debugging code, add little more comments and use constant strings.
Well done !

2022-05-05 14:55 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/kneetag/VisualizationUtils.kt
> +
You could add some comments that say: 
rightPerson.first!!.keyPoints[BodyPart.LEFT_KNEE.position].coordinate,
                            bodyPart.coordinate
                        ) < TRESHOLD_TO_WIN 
Something like "right person touched the left knee"
And 
result = 1
Something like "rightPerson wins" 
It will help later when we will have to read back this code, and we can understand it without looking at the whole for loop

2022-05-05 14:55 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/kneetag/camera/CameraSource.kt
> +        System.out.println(result)
Remove debugging code when you create a PR

2022-05-05 14:55 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/kneetag/camera/CameraSource.kt
> +    public val main: MainActivity,
Why is it public ? You're not using it outside the class

2022-05-05 14:55 UTC, Tetardfurieux commented on app/src/main/res/layout-land/activity_gameended.xml
> +            android:text="TextView" />
Use constant string resource for this one too

2022-05-05 17:16 UTC, Antonio06188 approved these changes
Good code, think about using constant String instead of hardcode string like in the method onCreate of the class finishScreen

2022-05-06 07:34 UTC, Aco-Hub commented on app/src/main/java/ch/epfl/sdp/healthplay/kneetag/camera/CameraSource.kt
> +    var gameState = PLAYER_SELECTION
No because there are only 3 states.

2022-05-06 07:47 UTC, Tetardfurieux approved these changes
nice fix !

2022-05-06 13:26 UTC, merged