Scan friends' QR code and more product info
HealthPlay-EPFL/Health-Play pull request #203
Opened 2022-05-05 18:02 UTC by ozan-guven

2022-05-05 19:23 UTC, emonnin-epfl requested changes

2022-05-05 19:23 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanFragment.java
> +                                                    Toast t = Toast.makeText(getContext(), username+" was added in your friends list !", Toast.LENGTH_SHORT);
no need to create a variable t if you use it right after
(Toast.makeText(getContext(), username+" was added in your friends list !", Toast.LENGTH_SHORT).show();)

2022-05-05 19:23 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/model/Product.java
> +                joiner.add(name.substring(3));
Why 3?

2022-05-06 07:02 UTC, Aco-Hub approved these changes

2022-05-06 08:24 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/model/Product.java
> +                joiner.add(name.substring(3));
This is to trim the language in front of the ingredient. I should make it clearer.

2022-05-06 08:25 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/BarcodeScanFragment.java
> +                                                    Toast t = Toast.makeText(getContext(), username+" was added in your friends list !", Toast.LENGTH_SHORT);
You are right, will change this !

2022-05-06 08:35 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/model/Product.java
> +                joiner.add(name.substring(3));
OK, great!

2022-05-06 08:35 UTC, emonnin-epfl approved these changes

2022-05-06 08:43 UTC, merged