Feature/monthly leader board
HealthPlay-EPFL/Health-Play pull request #220
Opened 2022-05-10 11:29 UTC by emonnin-epfl

2022-05-10 13:01 UTC, Aco-Hub commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> +    public final static int STRING_MAX_LEN = 40;
unused constant

2022-05-10 13:04 UTC, Aco-Hub commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> +                    });
Why do you use a lambda? It seems like a lot of code that could be simpler

2022-05-10 13:11 UTC, Aco-Hub requested changes
Need some modifications/comments

2022-05-10 15:29 UTC, Antonio06188 requested changes
Good code but you use the same string many time, you can use a constant for that

2022-05-10 15:29 UTC, Antonio06188 commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> -                            if (!task.isSuccessful()) {
use constant for the string friends

2022-05-10 15:29 UTC, Antonio06188 commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> -                        });
Use constant string

2022-05-10 15:29 UTC, Antonio06188 commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> +    public final static int STRING_MAX_LEN = 40;
I think that STRING_MAX_LEN is unused

2022-05-10 15:29 UTC, Antonio06188 commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardFragment.java
> +        }
what is this arguments that you get?? Is it usefull??

2022-05-11 10:33 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> +    public final static int STRING_MAX_LEN = 40;
yes, good observation thank you!

2022-05-11 10:34 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> +                    });
This is the way firebase works, unfortunately nobody has found a way to do it differently.

2022-05-11 10:35 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> +    private void initTimer() {
I added them, thank you

2022-05-11 10:35 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/MonthlyLeaderBoardActivity.java
> +package ch.epfl.sdp.healthplay;
done

2022-05-11 10:39 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> -                            if (!task.isSuccessful()) {
Aco has already commented on this, try looking at other people's comments before making yours!

2022-05-11 10:39 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> -                        });
did it

2022-05-11 10:39 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> +    public final static int STRING_MAX_LEN = 40;
Aco has already commented on this, try looking at other people's comments before making yours!

2022-05-11 10:40 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardActivity.java
> -                            if (!task.isSuccessful()) {
done

2022-05-11 10:44 UTC, emonnin-epfl commented on app/src/main/java/ch/epfl/sdp/healthplay/LeaderBoardFragment.java
> +        }
the two leaderboards are still activities I did not have time to convert them into fragments

2022-05-11 10:47 UTC, Aco-Hub approved these changes

2022-05-11 15:25 UTC, merged