Fragment tests
HealthPlay-EPFL/Health-Play pull request #222
Opened 2022-05-11 20:13 UTC by Antonio06188

2022-05-12 19:15 UTC, Aco-Hub commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/GameMenuFragmentTest.java
>      }*/
why does this test is not applied?

2022-05-12 19:37 UTC, Aco-Hub commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/SignedInFragmentTest.java
> +        FirebaseAuth.getInstance().signInWithEmailAndPassword("HP@admin.ch", "123456");
You can use a before statement toalways execute this.

2022-05-12 19:37 UTC, Aco-Hub reviewed
Some things to change

2022-05-12 21:48 UTC, emonnin-epfl requested changes

2022-05-12 21:48 UTC, emonnin-epfl commented on app/build.gradle
> +    androidTestImplementation "org.mockito:mockito-core:4.4.0"
I don't see anywhere that you use mockito for android tests.

2022-05-12 21:48 UTC, emonnin-epfl commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/AuthUiActivityTest.java
> +        onView(withHint("Email")).perform(typeText("HP@admin.ch"), ViewActions.closeSoftKeyboard());
I see you use this email all the time, maybe you could make it a constant

2022-05-12 21:48 UTC, emonnin-epfl commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/AuthUiActivityTest.java
> +        FirebaseAuth.getInstance().signInWithEmailAndPassword("HP@admin.ch", "123456");
same thing as for the email but for the password

2022-05-12 21:48 UTC, emonnin-epfl commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/Frag_HomeTest.java
> +    /*@Rule
there are a lot of commented lines of code, maybe you could remove some of them

2022-05-13 07:31 UTC, Antonio06188 commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/GameMenuFragmentTest.java
>      }*/
Because the version of kneetag on my branch connot be launch

2022-05-13 07:44 UTC, Antonio06188 commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/Frag_HomeTest.java
> +    /*@Rule
I try to create the test but I can't do it, so I don't change the class

2022-05-13 07:58 UTC, Aco-Hub approved these changes

2022-05-13 08:19 UTC, emonnin-epfl approved these changes

2022-05-13 10:44 UTC, merged