Create list for products
HealthPlay-EPFL/Health-Play pull request #225
Opened 2022-05-12 13:31 UTC by ozan-guven

2022-05-12 19:44 UTC, Zephyr75 requested changes
Really nice code and especially good comments except in one class, good job!

2022-05-12 19:44 UTC, Zephyr75 commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/RecyclerViewAdapter.java
> +public class RecyclerViewAdapter extends RecyclerView.Adapter<RecyclerViewAdapter.ViewHolder> {
Add some comments to this class

2022-05-12 19:44 UTC, Zephyr75 commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/ProductListFragment.java
> +    public View onCreateView(LayoutInflater inflater, ViewGroup container,
Very nice comments in this class, good job!

2022-05-12 19:44 UTC, Zephyr75 commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/RecyclerViewAdapter.java
> +            Log.d(TAG, "onBindViewHolder: clicked");
This string could be made into a constant

2022-05-12 20:11 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/RecyclerViewAdapter.java
> +            Log.d(TAG, "onBindViewHolder: clicked");
I'm not sure about this one. This string is auto generated when you create the log. Besides this, it has not much to do with the class itself, so I think making it into a constant would break the point of the log. What do you think ?

2022-05-12 22:24 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/RecyclerViewAdapter.java
> +public class RecyclerViewAdapter extends RecyclerView.Adapter<RecyclerViewAdapter.ViewHolder> {
Done !

2022-05-12 23:23 UTC, Tetardfurieux requested changes
Great code overall, great comments where you put some (please add more where I reviewed).
Also, you can remove the ARGS of a fragment if you're not using them.
Keep it up this way ! :D

2022-05-12 23:23 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileFragment.java
>      }
Good use of a custom Listener !

2022-05-12 23:23 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/Database.java
> +    public void addProduct(String userId, String productCode) {
Missing a comment here ! Even tho the name is self explanatory, you should always comment your functions :)

2022-05-12 23:23 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/ProductListFragment.java
> +    private static final String ARG_PARAM2 = "param2";
Remove unecessary args + TODO. If you're not using args it will count as a non covered line in your tests

2022-05-12 23:23 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/ProductListFragment.java
> +    private String mParam2;
Same here, remove them + remove TODO

2022-05-12 23:23 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/ProductListFragment.java
> +        fragment.setArguments(args);
same here, you can remove them + remove TODO

2022-05-12 23:23 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/ProductListFragment.java
> +            mParam2 = getArguments().getString(ARG_PARAM2);
+1

2022-05-12 23:23 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/ProductListFragment.java
> +    private void initRecyclerView(View view) {
Please add a comment here

2022-05-12 23:23 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/ProductListFragment.java
> +    private void initProductsAndDates(View view) {
Please add a comment here

2022-05-12 23:23 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/RecyclerViewAdapter.java
> +    public static class ViewHolder extends RecyclerView.ViewHolder {
Great use of the ViewHolder class !

2022-05-12 23:23 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/RecyclerViewAdapter.java
> +        RelativeLayout productListLayout;
Make these variables private

2022-05-13 08:18 UTC, Zephyr75 commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/RecyclerViewAdapter.java
> +            Log.d(TAG, "onBindViewHolder: clicked");
It's fine then!

2022-05-13 08:19 UTC, Zephyr75 approved these changes

2022-05-13 08:26 UTC, Tetardfurieux approved these changes

2022-05-13 08:27 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/productlist/ProductListFragment.java
> +    private static final String ARG_PARAM2 = "param2";
Good call !

2022-05-13 08:27 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/database/Database.java
> +    public void addProduct(String userId, String productCode) {
Got it !

2022-05-13 08:50 UTC, merged