Offline Mode for Profile + create Test
HealthPlay-EPFL/Health-Play pull request #260
Opened 2022-05-25 18:42 UTC by Antonio06188

2022-05-25 19:57 UTC, ozan-guven requested changes
Overall, good code. You can look for my comments.

2022-05-25 19:57 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +                    //userStats = convert();
Why is this line commented ? If it is not useful, why not removing it altogether ?

2022-05-25 19:57 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +            /*database.mDatabase.child("users").child(user.getUid()).child("stats").child(date).addValueEventListener(new ValueEventListener() {
You should remove those lines of code if they are commented ?

2022-05-25 19:57 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +                if (selectedDate != null && selectedDate.equals(date)) {
You could collapse these two if's into one if statement.

2022-05-25 19:57 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +    /*private void constructUserStats(FirebaseUser user){
Why are those lines commented out ?

2022-05-25 19:57 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +        /*userStats = null;
Why are those lines commented ?

2022-05-25 19:57 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +    /*private Map<String, Map<String, String>> convert(){
Same here as above

2022-05-25 19:57 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/QrCodeFragment.java
> +        //Bitmap myBitmap = QRCode.from(FirebaseAuth.getInstance().getCurrentUser().getUid()).bitmap();
This line seems useless as it is commented ?

2022-05-25 19:57 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileFragment.java
> +
You could add some comments in this section so that we can better understand what this function does in the future.

2022-05-25 19:57 UTC, ozan-guven commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileFragment.java
> +        db.mDatabase.child(Database.USERS).child(userId).child(Database.IMAGE).addValueEventListener(new ValueEventListener() {
Very good that you made the string into a constant !

2022-05-25 20:10 UTC, Antonio06188 commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileFragment.java
> +        db.mDatabase.child(Database.USERS).child(userId).child(Database.IMAGE).addValueEventListener(new ValueEventListener() {
Thanks

2022-05-25 20:11 UTC, Antonio06188 commented on app/src/main/java/ch/epfl/sdp/healthplay/QrCodeFragment.java
> +        //Bitmap myBitmap = QRCode.from(FirebaseAuth.getInstance().getCurrentUser().getUid()).bitmap();
I've forgotten this lines because I modified files and I kept this comment lines for backup

2022-05-25 20:14 UTC, Antonio06188 commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +                if (selectedDate != null && selectedDate.equals(date)) {
I prefer it this way because I think it's clearer for people who read the code

2022-05-25 20:43 UTC, Tetardfurieux requested changes
Great code overall. Good modularity.
Try to add more comments to your functions (with /** block) and some comments In the function too (some big coding block without space is not easy to read)

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/BarcodeScanFragmentTest.java
> +        TimeUnit.SECONDS.sleep(5);
I think 5 seconds is excessive, maybe try to reduce

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/ProfileSettingsActivityTest.java
> +        ViewActions.closeSoftKeyboard();
Is it necessary to close the keyboard between each "typeText"

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/planthunt/PlanthuntNewPlantActivityTest.java
> +    }*/
Why did you remove the whole test class ?

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +        userStats = WelcomeScreenActivity.cache.getDataMapCalendar();
Is it safe if there is nothing in the cache ?

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
>              });
Do some cleanup in this class, if it is not usefull anymore it shouldn't be there

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +            /*database.mDatabase.child("users").child(user.getUid()).child("stats").child(date).addValueEventListener(new ValueEventListener() {
+1

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/Frag_Home.java
> +    /*private void constructUserStats(FirebaseUser user){
+1

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileFragment.java
> +        }
It's pretty messy to put everything here without space.
Also add some comments maybe

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/auth/ProfileFragment.java
> +        view.findViewById(R.id.goToProductList).setVisibility(View.VISIBLE);
Is this part really necessary ? Usually it is Enabled and visible by default

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/DataCache.java
> +                    listenField(user.getUid(), Database.IMAGE);
Great use of a function here !

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/DataCache.java
> +                    //Log.d("Ecriture", json);
Remove debugging code hier

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/DataCache.java
> +    private void store(String userId){
Add /** comment block + some comments in the function

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/DataCache.java
> +    private String getStringFromBitmap(Bitmap bitmapPicture) {
/** comment block missing

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/DataCache.java
>      public Map<String, Map<String, Number>> getDataMap(){
/** comment block missing too

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/DataCache.java
> +    public Map<String, Map<String, String>> getDataMapCalendar(){
Add comment to the function

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/DataCache.java
> +    public String getField(String field){
Add comments

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/DataCache.java
> +    public Bitmap getQrCode(){
Add comments

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/ParseDataGraph.java
> +                mapData.put(date, dataParse);
Maybe try to do some space in the code, and add comments

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/User.java
> +    public int getLastCurrentWeight() {
Add comments

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/database/User.java
> +    public void setLastCurrentWeight(int lastCurrentWeight) {
Add comments

2022-05-25 20:43 UTC, Tetardfurieux commented on app/src/main/java/ch/epfl/sdp/healthplay/model/Graph_Frag.java
> +        initBarChart(view);
Great use of functions here !

2022-05-25 21:29 UTC, Antonio06188 commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/ProfileSettingsActivityTest.java
> +        ViewActions.closeSoftKeyboard();
Yes because if the devices is smaller, maybe the test failed because it cannot click on the text

2022-05-25 21:30 UTC, Antonio06188 commented on app/src/androidTest/java/ch/epfl/sdp/healthplay/planthunt/PlanthuntNewPlantActivityTest.java
> +    }*/
Because it's broken, and not only on my branch

2022-05-25 23:21 UTC, ozan-guven approved these changes
Good job !

2022-05-26 00:06 UTC, Tetardfurieux approved these changes

2022-05-26 13:31 UTC, merged